export const FETCH_ACCOUNT_DETAILS_REQUEST = "FETCH_ACCOUNT_DETAILS_REQUEST";
export const FETCH_ACCOUNT_DETAILS_SUCCESS = "FETCH_ACCOUNT_DETAILS_SUCCESS";
export const FETCH_ACCOUNT_DETAILS_FAILURE = "FETCH_ACCOUNT_DETAILS_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";