export const ADD_COMMENT_REQ = "ADD_COMMENT_REQ"
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE"

export const GET_NEWS_DATA_REQ = "GET_NEWS_DATA_REQ";
export const GET_NEWS_DATA_SUCCESS = "GET_NEWS_DATA_SUCCESS"
export const GET_NEWS_DATA_FAILURE = "GET_NEWS_DATA_FAILURE"

export const DELETE_COMMENT_REQ = "DELETE_COMMENT_REQ"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE"

export const EDIT_COMMENT_REQ = "EDIT_COMMENT_REQ"
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS"
export const EDIT_COMMENT_FAILURE = "EDIT_COMMENT_FAILURE"