export const FETCH_SEARCH_KEYWORDS_REQUEST = "FETCH_SEARCH_KEYWORDS_REQUEST";
export const FETCH_SEARCH_KEYWORDS_SUCCESS = "FETCH_SEARCH_KEYWORDS_SUCCESS";
export const FETCH_SEARCH_KEYWORDS_FAILURE = "FETCH_SEARCH_KEYWORDS_FAILURE";

export const FETCH_NEWS_REQUEST = "FETCH_NEWS_REQUEST";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE";