export const ADD_EVENT_DETAILS_REQ = "ADD_EVENT_DETAILS_REQ";
export const ADD_EVENT_DETAILS_SUCCESS = "ADD_EVENT_DETAILS_SUCCESS";
export const ADD_EVENT_DETAILS_FAILURE = "ADD_EVENT_DETAILS_FAILURE";
