export const POST_USER_SIGNUP_SUCCESS="POST_USER_SIGNUP_SUCCESS"
export const POST_USER_SIGNUP_FAILURE="POST_USER_SIGNUP_FAILURE"
export const POST_USER_SIGNUP_REQUEST="POST_USER_SIGNUP_REQUEST"

export const GET_USER_SIGNUP_SUCCESS="GET_USER_SIGNUP_SUCCESS"
export const GET_USER_SIGNUP_FAILURE="GET_USER_SIGNUP_FAILURE"
export const GET_USER_SIGNUP_REQUEST="GET_USER_SIGNUP_REQUEST"

export const SIGNIN="SIGNIN"
export const SIGNUP="SIGNUP"
export const IS_AUTH="IS_AUTH"
export const IS_OPEN="IS_OPEN"
export const CLOSE_OPEN="CLOSE_OPEN"

export const LOGOUT_USER = "LOGOUT_USER"