export const FETCH_NEWS_HEADLINE_REQUEST = "FETCH_NEWS_HEADLINE_REQUEST";
export const FETCH_NEWS_HEADLINE_SUCCESS = "FETCH_NEWS_HEADLINE_SUCCESS";
export const FETCH_NEWS_HEADLINE_FAILURE = "FETCH_NEWS_HEADLINE_FAILURE";