export const GET_NEWSLETTERS_REQ = "GET_NEWSLETTERS_REQ";
export const GET_NEWSLETTERS_SUCCESS = "GET_NEWSLETTERS_SUCCESS";
export const GET_NEWSLETTERS_FAILURE = "GET_NEWSLETTERS_FAILURE";

export const ADD_NEWSLETTERS_REQ = "ADD_NEWSLETTERS_REQ";
export const ADD_NEWSLETTERS_SUCCESS = "ADD_NEWSLETTERS_SUCCESS";
export const ADD_NEWSLETTERS_FAILURE = "ADD_NEWSLETTERS_FAILURE";
