export const FETCH_STARTUP_NEWS_REQUEST = "FETCH_STARTUP_NEWS_REQUEST";
export const FETCH_STARTUP_NEWS_SUCCESS = "FETCH_STARTUP_NEWS_SUCCESS";
export const FETCH_STARTUP_NEWS_FAILURE = "FETCH_STARTUP_NEWS_FAILURE";